CREATE TABLE IF NOT EXISTS patient_records (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  reporting_period text NOT NULL,
  source_program text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),

  tipo_registro integer DEFAULT 2,
  codigo_habilitacion_ips text DEFAULT '761471222301',
  tipo_identificacion text,
  numero_identificacion text,
  primer_apellido text,
  segundo_apellido text DEFAULT 'NONE',
  primer_nombre text,
  segundo_nombre text DEFAULT 'NONE',
  fecha_nacimiento text,
  sexo text,
  codigo_pertenencia_etnica integer DEFAULT 6,
  codigo_ocupacion text DEFAULT '9999',
  codigo_nivel_educativo integer DEFAULT 13,
  gestante integer DEFAULT 0,
  sifilis_gestacional_congenita integer DEFAULT 0,
  resultado_prueba_mini_mental integer DEFAULT 0,
  hipotiroidismo_congenito integer DEFAULT 0,
  sintomatico_respiratorio integer DEFAULT 21,
  consumo_tabaco integer DEFAULT 99,
  lepra integer DEFAULT 21,
  obesidad_desnutricion integer DEFAULT 21,
  resultado_tacto_rectal integer DEFAULT 0,
  acido_folico_preconcepcional integer DEFAULT 0,
  resultado_sangre_oculta_fecal integer DEFAULT 0,
  enfermedad_mental integer DEFAULT 21,
  cancer_cervix integer DEFAULT 0,
  agudeza_visual_ojo_izquierdo integer DEFAULT 0,
  agudeza_visual_ojo_derecho integer DEFAULT 0,
  fecha_peso text DEFAULT '1800-01-01',
  peso_kilogramos numeric DEFAULT 999,
  fecha_talla text DEFAULT '1800-01-01',
  talla_centimetros integer DEFAULT 999,
  fecha_probable_parto text DEFAULT '1845-01-01',
  codigo_pais integer DEFAULT 170,
  clasificacion_riesgo_gestacional integer DEFAULT 0,
  resultado_colonoscopia_tamizaje integer DEFAULT 0,
  resultado_tamizaje_auditivo_neonatal integer DEFAULT 0,
  resultado_tamizaje_visual_neonatal integer DEFAULT 0,
  dpt_menores_5_anios integer DEFAULT 0,
  resultado_tamizaje_vale integer DEFAULT 0,
  neumococo integer DEFAULT 0,
  resultado_tamizaje_hepatitis_c integer DEFAULT 0,
  resultado_escala_motricidad_gruesa integer DEFAULT 0,
  resultado_escala_motricidad_finoadaptativa integer DEFAULT 0,
  resultado_escala_personal_social integer DEFAULT 0,
  resultado_escala_audicion_lenguaje integer DEFAULT 0,
  tratamiento_ablativo_escision integer DEFAULT 0,
  resultado_tamizaje_oximetria integer DEFAULT 0,
  fecha_atencion_parto_cesarea text DEFAULT '1845-01-01',
  fecha_salida_atencion_parto text DEFAULT '1845-01-01',
  fecha_atencion_lactancia_materna text DEFAULT '1845-01-01',
  fecha_consulta_valoracion_integral text DEFAULT '1845-01-01',
  fecha_asesoria_anticoncepcion text DEFAULT '1845-01-01',
  suministro_metodo_anticonceptivo integer DEFAULT 0,
  fecha_suministro_anticonceptivo text DEFAULT '1845-01-01',
  fecha_primera_consulta_prenatal text DEFAULT '1845-01-01',
  resultado_glicemia_basal integer DEFAULT 0,
  fecha_ultimo_control_prenatal text DEFAULT '1845-01-01',
  suministro_acido_folico_prenatal integer DEFAULT 0,
  suministro_sulfato_ferroso_prenatal integer DEFAULT 0,
  suministro_carbonato_calcio_prenatal integer DEFAULT 0,
  fecha_valoracion_agudeza_visual text DEFAULT '1845-01-01',
  fecha_tamizaje_vale text DEFAULT '1845-01-01',
  fecha_tacto_rectal text DEFAULT '1845-01-01',
  fecha_tamizaje_oximetria text DEFAULT '1845-01-01',
  fecha_colonoscopia_tamizaje text DEFAULT '1845-01-01',
  fecha_sangre_oculta_fecal text DEFAULT '1845-01-01',
  consulta_psicologia text DEFAULT '1845-01-01',
  fecha_tamizaje_auditivo_neonatal text DEFAULT '1845-01-01',
  suministro_fortificacion_casera integer DEFAULT 0,
  suministro_vitamina_a integer DEFAULT 0,
  fecha_toma_ldl text DEFAULT '1845-01-01',
  fecha_toma_psa text DEFAULT '1845-01-01',
  preservativos_entregados_its integer DEFAULT 0,
  fecha_tamizaje_visual_neonatal text DEFAULT '1845-01-01',
  fecha_atencion_salud_bucal text DEFAULT '1845-01-01',
  suministro_hierro_primera_infancia integer DEFAULT 0,
  fecha_antigeno_hepatitis_b text DEFAULT '1845-01-01',
  resultado_antigeno_hepatitis_b integer DEFAULT 0,
  fecha_tamizaje_sifilis text DEFAULT '1845-01-01',
  resultado_tamizaje_sifilis integer DEFAULT 0,
  fecha_prueba_vih text DEFAULT '1845-01-01',
  resultado_prueba_vih integer DEFAULT 0,
  fecha_tsh_neonatal text DEFAULT '1845-01-01',
  resultado_tsh_neonatal integer DEFAULT 0,
  tamizaje_cancer_cuello_uterino integer DEFAULT 0,
  fecha_tamizaje_cancer_cuello_uterino text DEFAULT '1845-01-01',
  resultado_tamizaje_cancer_cuello_uterino integer DEFAULT 0,
  calidad_muestra_citologia integer DEFAULT 0,
  codigo_habilitacion_tamizaje_cuello integer DEFAULT 0,
  fecha_colposcopia text DEFAULT '1845-01-01',
  resultado_ldl integer DEFAULT 0,
  fecha_biopsia_cervicouterina text DEFAULT '1845-01-01',
  resultado_biopsia_cervicouterina integer DEFAULT 0,
  resultado_hdl integer DEFAULT 0,
  fecha_toma_mamografia text DEFAULT '1845-01-01',
  resultado_mamografia integer DEFAULT 0,
  resultado_trigliceridos integer DEFAULT 0,
  fecha_biopsia_mama text DEFAULT '1845-01-01',
  fecha_resultado_biopsia_mama text DEFAULT '1845-01-01',
  resultado_biopsia_mama integer DEFAULT 0,
  cop_por_persona integer DEFAULT 0,
  fecha_toma_hemoglobina text DEFAULT '1845-01-01',
  resultado_hemoglobina numeric DEFAULT 0,
  fecha_toma_glicemia_basal text DEFAULT '1845-01-01',
  fecha_toma_creatinina text DEFAULT '1845-01-01',
  resultado_creatinina numeric DEFAULT 0,
  preservativos_entregados_its_fecha text DEFAULT '1845-01-01',
  resultado_psa numeric DEFAULT 0,
  fecha_tamizaje_hepatitis_c text DEFAULT '1845-01-01',
  fecha_toma_hdl text DEFAULT '1845-01-01',
  fecha_toma_baciloscopia text DEFAULT '1845-01-01',
  resultado_baciloscopia integer DEFAULT 21,
  clasificacion_riesgo_cardiovascular integer DEFAULT 0,
  tratamiento_sifilis_gestacional integer DEFAULT 0,
  tratamiento_sifilis_congenita integer DEFAULT 0,
  clasificacion_riesgo_metabolico integer DEFAULT 0,
  fecha_toma_trigliceridos text DEFAULT '1845-01-01',

  UNIQUE(numero_identificacion, reporting_period, source_program)
);

CREATE INDEX IF NOT EXISTS idx_patient_period ON patient_records(reporting_period);
CREATE INDEX IF NOT EXISTS idx_patient_program ON patient_records(source_program);
CREATE INDEX IF NOT EXISTS idx_patient_identification ON patient_records(numero_identificacion);

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER patient_records_updated_at
  BEFORE UPDATE ON patient_records
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();
