const COLUMNS_202 = [
  { index: 0, name: 'tipo_registro', label: 'Tipo de registro', type: 'N', maxLength: 1, required: true, defaultValue: 2, allowedValues: [1, 2], group: 'registro' },
  { index: 1, name: 'consecutivo_registro', label: 'Consecutivo de registro', type: 'N', maxLength: 8, required: true, defaultValue: null, allowedValues: null, group: 'registro' },
  { index: 2, name: 'codigo_habilitacion_ips', label: 'Codigo de habilitacion IPS primaria', type: 'N', maxLength: 12, required: true, defaultValue: '761471222301', allowedValues: null, group: 'identificacion' },
  { index: 3, name: 'tipo_identificacion', label: 'Tipo de identificacion del usuario', type: 'A', maxLength: 2, required: true, defaultValue: null, allowedValues: ['CC', 'TI', 'RC', 'CE', 'PA', 'CD', 'PE', 'SC', 'DE', 'MS', 'AS', 'CN'], group: 'identificacion' },
  { index: 4, name: 'numero_identificacion', label: 'Numero de identificacion del usuario', type: 'A', maxLength: 18, required: true, defaultValue: null, allowedValues: null, group: 'identificacion' },
  { index: 5, name: 'primer_apellido', label: 'Primer apellido del usuario', type: 'A', maxLength: 30, required: true, defaultValue: null, allowedValues: null, group: 'identificacion' },
  { index: 6, name: 'segundo_apellido', label: 'Segundo apellido del usuario', type: 'A', maxLength: 30, required: false, defaultValue: 'NONE', allowedValues: null, group: 'identificacion' },
  { index: 7, name: 'primer_nombre', label: 'Primer nombre del usuario', type: 'A', maxLength: 30, required: true, defaultValue: null, allowedValues: null, group: 'identificacion' },
  { index: 8, name: 'segundo_nombre', label: 'Segundo nombre del usuario', type: 'A', maxLength: 30, required: false, defaultValue: 'NONE', allowedValues: null, group: 'identificacion' },
  { index: 9, name: 'fecha_nacimiento', label: 'Fecha de nacimiento', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'identificacion' },
  { index: 10, name: 'sexo', label: 'Sexo', type: 'A', maxLength: 1, required: true, defaultValue: null, allowedValues: ['M', 'F'], group: 'identificacion' },
  { index: 11, name: 'codigo_pertenencia_etnica', label: 'Codigo pertenencia etnica', type: 'N', maxLength: 1, required: true, defaultValue: 6, allowedValues: [1, 2, 3, 4, 5, 6], group: 'identificacion' },
  { index: 12, name: 'codigo_ocupacion', label: 'Codigo de ocupacion', type: 'N', maxLength: 4, required: true, defaultValue: null, allowedValues: null, group: 'identificacion' },
  { index: 13, name: 'codigo_nivel_educativo', label: 'Codigo nivel educativo', type: 'N', maxLength: 2, required: true, defaultValue: 13, allowedValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], group: 'identificacion' },
  { index: 14, name: 'gestante', label: 'Gestante', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 2, 21], group: 'gestacion' },
  { index: 15, name: 'sifilis_gestacional_congenita', label: 'Sifilis gestacional o congenita', type: 'N', maxLength: 2, required: true, defaultValue: 0, allowedValues: [0, 1], group: 'no_aplica' },
  { index: 16, name: 'resultado_mini_mental', label: 'Resultado prueba mini-mental state', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'vejez' },
  { index: 17, name: 'hipotiroidismo_congenito', label: 'Hipotiroidismo congenito', type: 'N', maxLength: 2, required: true, defaultValue: 0, allowedValues: [0, 1], group: 'no_aplica' },
  { index: 18, name: 'sintomatico_respiratorio', label: 'Sintomatico respiratorio', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [1, 2, 21], group: 'tuberculosis' },
  { index: 19, name: 'consumo_tabaco', label: 'Consumo de tabaco', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 20, name: 'lepra', label: 'Lepra', type: 'N', maxLength: 2, required: true, defaultValue: 21, allowedValues: [21, 1], group: 'no_aplica' },
  { index: 21, name: 'obesidad_desnutricion', label: 'Obesidad o desnutricion proteico calorica', type: 'N', maxLength: 2, required: true, defaultValue: 21, allowedValues: [21, 1], group: 'no_aplica' },
  { index: 22, name: 'resultado_tacto_rectal', label: 'Resultado del tacto rectal', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'ca_prostata' },
  { index: 23, name: 'acido_folico_preconcepcional', label: 'Acido folico preconcepcional', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 2, 21], group: 'gestacion' },
  { index: 24, name: 'resultado_sangre_oculta', label: 'Resultado sangre oculta materia fecal', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 6, 21], group: 'ca_colon' },
  { index: 25, name: 'enfermedad_mental', label: 'Enfermedad mental', type: 'N', maxLength: 2, required: true, defaultValue: 21, allowedValues: [21, 1], group: 'no_aplica' },
  { index: 26, name: 'cancer_cervix', label: 'Cancer de cervix', type: 'N', maxLength: 2, required: true, defaultValue: 0, allowedValues: [0, 1], group: 'no_aplica' },
  { index: 27, name: 'agudeza_visual_ojo_izquierdo', label: 'Agudeza visual lejana ojo izquierdo', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 3, 4, 5, 6, 7, 8, 9, 21], group: 'agudeza_visual' },
  { index: 28, name: 'agudeza_visual_ojo_derecho', label: 'Agudeza visual lejana ojo derecho', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 3, 4, 5, 6, 7, 8, 9, 21], group: 'agudeza_visual' },
  { index: 29, name: 'fecha_peso', label: 'Fecha del peso', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'toda_poblacion' },
  { index: 30, name: 'peso_kilogramos', label: 'Peso en kilogramos', type: 'D', maxLength: 5, required: true, defaultValue: null, allowedValues: null, group: 'toda_poblacion' },
  { index: 31, name: 'fecha_talla', label: 'Fecha de la talla', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'toda_poblacion' },
  { index: 32, name: 'talla_centimetros', label: 'Talla en centimetros', type: 'N', maxLength: 3, required: true, defaultValue: null, allowedValues: null, group: 'toda_poblacion' },
  { index: 33, name: 'fecha_probable_parto', label: 'Fecha probable de parto', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'gestacion' },
  { index: 34, name: 'codigo_pais', label: 'Codigo pais', type: 'N', maxLength: 3, required: true, defaultValue: 170, allowedValues: null, group: 'identificacion' },
  { index: 35, name: 'clasificacion_riesgo_gestacional', label: 'Clasificacion riesgo gestacional', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'gestacion' },
  { index: 36, name: 'resultado_colonoscopia', label: 'Resultado colonoscopia tamizaje', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 2, 3, 4, 5, 6, 21], group: 'ca_colon' },
  { index: 37, name: 'resultado_tamizaje_auditivo', label: 'Resultado tamizaje auditivo neonatal', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'recien_nacido' },
  { index: 38, name: 'resultado_tamizaje_visual_neonatal', label: 'Resultado tamizaje visual neonatal', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'recien_nacido' },
  { index: 39, name: 'dpt_menores_5', label: 'DPT menores de 5 anos', type: 'N', maxLength: 2, required: true, defaultValue: 0, allowedValues: [0, 1], group: 'no_aplica' },
  { index: 40, name: 'resultado_tamizaje_vale', label: 'Resultado tamizaje VALE', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'test_0_12' },
  { index: 41, name: 'neumococo', label: 'Neumococo', type: 'N', maxLength: 2, required: true, defaultValue: 0, allowedValues: [0, 1], group: 'no_aplica' },
  { index: 42, name: 'resultado_hepatitis_c', label: 'Resultado tamizaje hepatitis C', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'toda_poblacion' },
  { index: 43, name: 'resultado_motricidad_gruesa', label: 'Resultado escala desarrollo motricidad gruesa', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 3, 4, 5, 21], group: 'test_0_12' },
  { index: 44, name: 'resultado_motricidad_fina', label: 'Resultado escala desarrollo motricidad finoadaptativa', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 3, 4, 5, 21], group: 'test_0_12' },
  { index: 45, name: 'resultado_personal_social', label: 'Resultado escala desarrollo personal social', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 3, 4, 5, 21], group: 'test_0_12' },
  { index: 46, name: 'resultado_audicion_lenguaje', label: 'Resultado escala desarrollo audicion lenguaje', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 3, 4, 5, 21], group: 'test_0_12' },
  { index: 47, name: 'tratamiento_ablativo', label: 'Tratamiento ablativo escision', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 6, 7, 8, 9, 10, 21], group: 'ca_cervix' },
  { index: 48, name: 'resultado_oximetria', label: 'Resultado oximetria pre y post ductal', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'recien_nacido' },
  { index: 49, name: 'fecha_atencion_parto', label: 'Fecha atencion parto o cesarea', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'gestacion' },
  { index: 50, name: 'fecha_salida_parto', label: 'Fecha salida atencion parto o cesarea', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'gestacion' },
  { index: 51, name: 'fecha_lactancia_materna', label: 'Fecha atencion lactancia materna', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'gestacion' },
  { index: 52, name: 'fecha_consulta_valoracion', label: 'Fecha consulta valoracion integral', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'toda_poblacion' },
  { index: 53, name: 'fecha_asesoria_anticoncepcion', label: 'Fecha asesoria anticoncepcion', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'anticoncepcion' },
  { index: 54, name: 'suministro_metodo_anticonceptivo', label: 'Suministro metodo anticonceptivo', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21], group: 'anticoncepcion' },
  { index: 55, name: 'fecha_suministro_anticonceptivo', label: 'Fecha suministro metodo anticonceptivo', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'anticoncepcion' },
  { index: 56, name: 'fecha_primera_consulta_prenatal', label: 'Fecha primera consulta prenatal', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'gestacion' },
  { index: 57, name: 'resultado_glicemia', label: 'Resultado glicemia basal', type: 'N', maxLength: 3, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 58, name: 'fecha_ultimo_control_prenatal', label: 'Fecha ultimo control prenatal', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'gestacion' },
  { index: 59, name: 'suministro_acido_folico_prenatal', label: 'Suministro acido folico control prenatal', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 16, 17, 18, 20, 21], group: 'gestacion' },
  { index: 60, name: 'suministro_sulfato_ferroso', label: 'Suministro sulfato ferroso control prenatal', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 16, 17, 18, 20, 21], group: 'gestacion' },
  { index: 61, name: 'suministro_carbonato_calcio', label: 'Suministro carbonato de calcio control prenatal', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 16, 17, 18, 20, 21], group: 'gestacion' },
  { index: 62, name: 'fecha_agudeza_visual', label: 'Fecha valoracion agudeza visual', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'agudeza_visual' },
  { index: 63, name: 'fecha_tamizaje_vale', label: 'Fecha tamizaje VALE', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'test_0_12' },
  { index: 64, name: 'fecha_tacto_rectal', label: 'Fecha tacto rectal', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_prostata' },
  { index: 65, name: 'fecha_oximetria', label: 'Fecha oximetria pre y post ductal', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'recien_nacido' },
  { index: 66, name: 'fecha_colonoscopia', label: 'Fecha colonoscopia tamizaje', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_colon' },
  { index: 67, name: 'fecha_sangre_oculta', label: 'Fecha sangre oculta materia fecal', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_colon' },
  { index: 68, name: 'consulta_psicologia', label: 'Consulta de psicologia', type: 'F', maxLength: 10, required: true, defaultValue: '1845-01-01', allowedValues: ['1845-01-01'], group: 'no_aplica' },
  { index: 69, name: 'fecha_tamizaje_auditivo', label: 'Fecha tamizaje auditivo neonatal', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'recien_nacido' },
  { index: 70, name: 'suministro_fortificacion_casera', label: 'Suministro fortificacion casera', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 16, 17, 18, 20, 21], group: 'primera_infancia' },
  { index: 71, name: 'suministro_vitamina_a', label: 'Suministro vitamina A primera infancia', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 16, 17, 18, 20, 21], group: 'primera_infancia' },
  { index: 72, name: 'fecha_toma_ldl', label: 'Fecha toma LDL', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 73, name: 'fecha_toma_psa', label: 'Fecha toma PSA', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_prostata' },
  { index: 74, name: 'preservativos_its_1', label: 'Preservativos entregados pacientes ITS', type: 'N', maxLength: 3, required: true, defaultValue: 0, allowedValues: [0], group: 'no_aplica' },
  { index: 75, name: 'fecha_tamizaje_visual_neonatal', label: 'Fecha tamizaje visual neonatal', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'recien_nacido' },
  { index: 76, name: 'fecha_salud_bucal', label: 'Fecha atencion salud bucal odontologia', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'cop' },
  { index: 77, name: 'suministro_hierro_primera_infancia', label: 'Suministro hierro primera infancia', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 16, 17, 18, 20, 21], group: 'primera_infancia' },
  { index: 78, name: 'fecha_hepatitis_b', label: 'Fecha antigeno superficie hepatitis B', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'toda_poblacion' },
  { index: 79, name: 'resultado_hepatitis_b', label: 'Resultado antigeno hepatitis B', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'toda_poblacion' },
  { index: 80, name: 'fecha_sifilis', label: 'Fecha tamizaje sifilis', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'toda_poblacion' },
  { index: 81, name: 'resultado_sifilis', label: 'Resultado tamizaje sifilis', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'toda_poblacion' },
  { index: 82, name: 'fecha_vih', label: 'Fecha prueba VIH', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'toda_poblacion' },
  { index: 83, name: 'resultado_vih', label: 'Resultado prueba VIH', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'toda_poblacion' },
  { index: 84, name: 'fecha_tsh_neonatal', label: 'Fecha TSH neonatal', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'recien_nacido' },
  { index: 85, name: 'resultado_tsh_neonatal', label: 'Resultado TSH neonatal', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 21], group: 'recien_nacido' },
  { index: 86, name: 'tamizaje_cancer_cervix', label: 'Tamizaje cancer cuello uterino', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 1, 2, 3, 4, 16, 17, 18, 19, 20, 21], group: 'ca_cervix' },
  { index: 87, name: 'fecha_tamizaje_cervix', label: 'Fecha tamizaje cancer cuello uterino', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_cervix' },
  { index: 88, name: 'resultado_tamizaje_cervix', label: 'Resultado tamizaje cancer cuello uterino', type: 'N', maxLength: 3, required: true, defaultValue: null, allowedValues: null, group: 'ca_cervix' },
  { index: 89, name: 'calidad_muestra_citologia', label: 'Calidad muestra citologia', type: 'N', maxLength: 3, required: true, defaultValue: null, allowedValues: [0, 1, 2, 3, 4, 999], group: 'ca_cervix' },
  { index: 90, name: 'codigo_ips_citologia', label: 'Codigo habilitacion IPS citologia', type: 'N', maxLength: 12, required: true, defaultValue: null, allowedValues: null, group: 'ca_cervix' },
  { index: 91, name: 'fecha_colposcopia', label: 'Fecha colposcopia', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_cervix' },
  { index: 92, name: 'resultado_ldl', label: 'Resultado LDL', type: 'N', maxLength: 12, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 93, name: 'fecha_biopsia_cervix', label: 'Fecha biopsia cervicouterina', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_cervix' },
  { index: 94, name: 'resultado_biopsia_cervix', label: 'Resultado biopsia cervicouterina', type: 'N', maxLength: 3, required: true, defaultValue: null, allowedValues: [0, 1, 3, 4, 5, 6, 21], group: 'ca_cervix' },
  { index: 95, name: 'resultado_hdl', label: 'Resultado HDL', type: 'N', maxLength: 12, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 96, name: 'fecha_mamografia', label: 'Fecha mamografia', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_mama' },
  { index: 97, name: 'resultado_mamografia', label: 'Resultado mamografia', type: 'N', maxLength: 3, required: true, defaultValue: null, allowedValues: [0, 1, 2, 3, 4, 5, 6, 7, 21], group: 'ca_mama' },
  { index: 98, name: 'resultado_trigliceridos', label: 'Resultado trigliceridos', type: 'N', maxLength: 12, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 99, name: 'fecha_biopsia_mama', label: 'Fecha biopsia mama', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_mama' },
  { index: 100, name: 'fecha_resultado_biopsia_mama', label: 'Fecha resultado biopsia mama', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'ca_mama' },
  { index: 101, name: 'resultado_biopsia_mama', label: 'Resultado biopsia mama', type: 'N', maxLength: 3, required: true, defaultValue: null, allowedValues: [0, 1, 2, 3, 4, 5, 21], group: 'ca_mama' },
  { index: 102, name: 'cop_persona', label: 'COP por persona', type: 'N', maxLength: 12, required: true, defaultValue: null, allowedValues: null, group: 'cop' },
  { index: 103, name: 'fecha_hemoglobina', label: 'Fecha toma hemoglobina', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 104, name: 'resultado_hemoglobina', label: 'Resultado hemoglobina', type: 'D', maxLength: 4, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 105, name: 'fecha_glicemia', label: 'Fecha toma glicemia basal', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 106, name: 'fecha_creatinina', label: 'Fecha toma creatinina', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 107, name: 'resultado_creatinina', label: 'Resultado creatinina', type: 'D', maxLength: 4, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 108, name: 'preservativos_its_2', label: 'Preservativos entregados pacientes ITS fecha', type: 'F', maxLength: 10, required: true, defaultValue: '1845-01-01', allowedValues: ['1845-01-01'], group: 'no_aplica' },
  { index: 109, name: 'resultado_psa', label: 'Resultado PSA', type: 'D', maxLength: 4, required: true, defaultValue: null, allowedValues: null, group: 'ca_prostata' },
  { index: 110, name: 'fecha_hepatitis_c', label: 'Fecha tamizaje hepatitis C', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'toda_poblacion' },
  { index: 111, name: 'fecha_toma_hdl', label: 'Fecha toma HDL', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
  { index: 112, name: 'fecha_baciloscopia', label: 'Fecha toma baciloscopia diagnostico', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'tuberculosis' },
  { index: 113, name: 'resultado_baciloscopia', label: 'Resultado baciloscopia', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [1, 2, 3, 4, 21], group: 'tuberculosis' },
  { index: 114, name: 'clasificacion_riesgo_cardiovascular', label: 'Clasificacion riesgo cardiovascular', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 6, 21], group: 'riesgo_cardiovascular' },
  { index: 115, name: 'tratamiento_sifilis_gestacional', label: 'Tratamiento sifilis gestacional', type: 'N', maxLength: 2, required: true, defaultValue: 0, allowedValues: [0, 1], group: 'no_aplica' },
  { index: 116, name: 'tratamiento_sifilis_congenita', label: 'Tratamiento sifilis congenita', type: 'N', maxLength: 2, required: true, defaultValue: 0, allowedValues: [0, 1], group: 'no_aplica' },
  { index: 117, name: 'clasificacion_riesgo_metabolico', label: 'Clasificacion riesgo metabolico', type: 'N', maxLength: 2, required: true, defaultValue: null, allowedValues: [0, 4, 5, 6, 21], group: 'riesgo_cardiovascular' },
  { index: 118, name: 'fecha_trigliceridos', label: 'Fecha toma trigliceridos', type: 'F', maxLength: 10, required: true, defaultValue: null, allowedValues: null, group: 'riesgo_cardiovascular' },
];

const AUXILIARY_COLUMNS = [
  { index: 119, name: 'cups', label: 'CUPS', type: 'A', group: 'auxiliar' },
  { index: 120, name: 'edad_anos', label: 'Edad actual EN AÑOS', type: 'N', group: 'auxiliar' },
  { index: 121, name: 'fecha_consulta', label: 'FECHA CONSULTA', type: 'F', group: 'auxiliar' },
];

export { COLUMNS_202, AUXILIARY_COLUMNS };
export default COLUMNS_202;
