const FIELD_DEFINITIONS = [
  { no: 0, col: 'tipo_registro', type: 'integer', default: 2 },
  { no: 2, col: 'codigo_habilitacion_ips', type: 'text', default: '761471222301' },
  { no: 3, col: 'tipo_identificacion', type: 'text', default: null },
  { no: 4, col: 'numero_identificacion', type: 'text', default: null },
  { no: 5, col: 'primer_apellido', type: 'text', default: null },
  { no: 6, col: 'segundo_apellido', type: 'text', default: 'NONE' },
  { no: 7, col: 'primer_nombre', type: 'text', default: null },
  { no: 8, col: 'segundo_nombre', type: 'text', default: 'NONE' },
  { no: 9, col: 'fecha_nacimiento', type: 'text', default: null },
  { no: 10, col: 'sexo', type: 'text', default: null },
  { no: 11, col: 'codigo_pertenencia_etnica', type: 'integer', default: 6 },
  { no: 12, col: 'codigo_ocupacion', type: 'text', default: '9999' },
  { no: 13, col: 'codigo_nivel_educativo', type: 'integer', default: 13 },
  { no: 14, col: 'gestante', type: 'integer', default: 0 },
  { no: 15, col: 'sifilis_gestacional_congenita', type: 'integer', default: 0 },
  { no: 16, col: 'resultado_prueba_mini_mental', type: 'integer', default: 0 },
  { no: 17, col: 'hipotiroidismo_congenito', type: 'integer', default: 0 },
  { no: 18, col: 'sintomatico_respiratorio', type: 'integer', default: 21 },
  { no: 19, col: 'consumo_tabaco', type: 'integer', default: 99 },
  { no: 20, col: 'lepra', type: 'integer', default: 21 },
  { no: 21, col: 'obesidad_desnutricion', type: 'integer', default: 21 },
  { no: 22, col: 'resultado_tacto_rectal', type: 'integer', default: 0 },
  { no: 23, col: 'acido_folico_preconcepcional', type: 'integer', default: 0 },
  { no: 24, col: 'resultado_sangre_oculta_fecal', type: 'integer', default: 0 },
  { no: 25, col: 'enfermedad_mental', type: 'integer', default: 21 },
  { no: 26, col: 'cancer_cervix', type: 'integer', default: 0 },
  { no: 27, col: 'agudeza_visual_ojo_izquierdo', type: 'integer', default: 0 },
  { no: 28, col: 'agudeza_visual_ojo_derecho', type: 'integer', default: 0 },
  { no: 29, col: 'fecha_peso', type: 'text', default: '1800-01-01' },
  { no: 30, col: 'peso_kilogramos', type: 'numeric', default: 999 },
  { no: 31, col: 'fecha_talla', type: 'text', default: '1800-01-01' },
  { no: 32, col: 'talla_centimetros', type: 'integer', default: 999 },
  { no: 33, col: 'fecha_probable_parto', type: 'text', default: '1845-01-01' },
  { no: 34, col: 'codigo_pais', type: 'integer', default: 170 },
  { no: 35, col: 'clasificacion_riesgo_gestacional', type: 'integer', default: 0 },
  { no: 36, col: 'resultado_colonoscopia_tamizaje', type: 'integer', default: 0 },
  { no: 37, col: 'resultado_tamizaje_auditivo_neonatal', type: 'integer', default: 0 },
  { no: 38, col: 'resultado_tamizaje_visual_neonatal', type: 'integer', default: 0 },
  { no: 39, col: 'dpt_menores_5_anios', type: 'integer', default: 0 },
  { no: 40, col: 'resultado_tamizaje_vale', type: 'integer', default: 0 },
  { no: 41, col: 'neumococo', type: 'integer', default: 0 },
  { no: 42, col: 'resultado_tamizaje_hepatitis_c', type: 'integer', default: 0 },
  { no: 43, col: 'resultado_escala_motricidad_gruesa', type: 'integer', default: 0 },
  { no: 44, col: 'resultado_escala_motricidad_finoadaptativa', type: 'integer', default: 0 },
  { no: 45, col: 'resultado_escala_personal_social', type: 'integer', default: 0 },
  { no: 46, col: 'resultado_escala_audicion_lenguaje', type: 'integer', default: 0 },
  { no: 47, col: 'tratamiento_ablativo_escision', type: 'integer', default: 0 },
  { no: 48, col: 'resultado_tamizaje_oximetria', type: 'integer', default: 0 },
  { no: 49, col: 'fecha_atencion_parto_cesarea', type: 'text', default: '1845-01-01' },
  { no: 50, col: 'fecha_salida_atencion_parto', type: 'text', default: '1845-01-01' },
  { no: 51, col: 'fecha_atencion_lactancia_materna', type: 'text', default: '1845-01-01' },
  { no: 52, col: 'fecha_consulta_valoracion_integral', type: 'text', default: '1845-01-01' },
  { no: 53, col: 'fecha_asesoria_anticoncepcion', type: 'text', default: '1845-01-01' },
  { no: 54, col: 'suministro_metodo_anticonceptivo', type: 'integer', default: 0 },
  { no: 55, col: 'fecha_suministro_anticonceptivo', type: 'text', default: '1845-01-01' },
  { no: 56, col: 'fecha_primera_consulta_prenatal', type: 'text', default: '1845-01-01' },
  { no: 57, col: 'resultado_glicemia_basal', type: 'integer', default: 0 },
  { no: 58, col: 'fecha_ultimo_control_prenatal', type: 'text', default: '1845-01-01' },
  { no: 59, col: 'suministro_acido_folico_prenatal', type: 'integer', default: 0 },
  { no: 60, col: 'suministro_sulfato_ferroso_prenatal', type: 'integer', default: 0 },
  { no: 61, col: 'suministro_carbonato_calcio_prenatal', type: 'integer', default: 0 },
  { no: 62, col: 'fecha_valoracion_agudeza_visual', type: 'text', default: '1845-01-01' },
  { no: 63, col: 'fecha_tamizaje_vale', type: 'text', default: '1845-01-01' },
  { no: 64, col: 'fecha_tacto_rectal', type: 'text', default: '1845-01-01' },
  { no: 65, col: 'fecha_tamizaje_oximetria', type: 'text', default: '1845-01-01' },
  { no: 66, col: 'fecha_colonoscopia_tamizaje', type: 'text', default: '1845-01-01' },
  { no: 67, col: 'fecha_sangre_oculta_fecal', type: 'text', default: '1845-01-01' },
  { no: 68, col: 'consulta_psicologia', type: 'text', default: '1845-01-01' },
  { no: 69, col: 'fecha_tamizaje_auditivo_neonatal', type: 'text', default: '1845-01-01' },
  { no: 70, col: 'suministro_fortificacion_casera', type: 'integer', default: 0 },
  { no: 71, col: 'suministro_vitamina_a', type: 'integer', default: 0 },
  { no: 72, col: 'fecha_toma_ldl', type: 'text', default: '1845-01-01' },
  { no: 73, col: 'fecha_toma_psa', type: 'text', default: '1845-01-01' },
  { no: 74, col: 'preservativos_entregados_its', type: 'integer', default: 0 },
  { no: 75, col: 'fecha_tamizaje_visual_neonatal', type: 'text', default: '1845-01-01' },
  { no: 76, col: 'fecha_atencion_salud_bucal', type: 'text', default: '1845-01-01' },
  { no: 77, col: 'suministro_hierro_primera_infancia', type: 'integer', default: 0 },
  { no: 78, col: 'fecha_antigeno_hepatitis_b', type: 'text', default: '1845-01-01' },
  { no: 79, col: 'resultado_antigeno_hepatitis_b', type: 'integer', default: 0 },
  { no: 80, col: 'fecha_tamizaje_sifilis', type: 'text', default: '1845-01-01' },
  { no: 81, col: 'resultado_tamizaje_sifilis', type: 'integer', default: 0 },
  { no: 82, col: 'fecha_prueba_vih', type: 'text', default: '1845-01-01' },
  { no: 83, col: 'resultado_prueba_vih', type: 'integer', default: 0 },
  { no: 84, col: 'fecha_tsh_neonatal', type: 'text', default: '1845-01-01' },
  { no: 85, col: 'resultado_tsh_neonatal', type: 'integer', default: 0 },
  { no: 86, col: 'tamizaje_cancer_cuello_uterino', type: 'integer', default: 0 },
  { no: 87, col: 'fecha_tamizaje_cancer_cuello_uterino', type: 'text', default: '1845-01-01' },
  { no: 88, col: 'resultado_tamizaje_cancer_cuello_uterino', type: 'integer', default: 0 },
  { no: 89, col: 'calidad_muestra_citologia', type: 'integer', default: 0 },
  { no: 90, col: 'codigo_habilitacion_tamizaje_cuello', type: 'integer', default: 0 },
  { no: 91, col: 'fecha_colposcopia', type: 'text', default: '1845-01-01' },
  { no: 92, col: 'resultado_ldl', type: 'integer', default: 0 },
  { no: 93, col: 'fecha_biopsia_cervicouterina', type: 'text', default: '1845-01-01' },
  { no: 94, col: 'resultado_biopsia_cervicouterina', type: 'integer', default: 0 },
  { no: 95, col: 'resultado_hdl', type: 'integer', default: 0 },
  { no: 96, col: 'fecha_toma_mamografia', type: 'text', default: '1845-01-01' },
  { no: 97, col: 'resultado_mamografia', type: 'integer', default: 0 },
  { no: 98, col: 'resultado_trigliceridos', type: 'integer', default: 0 },
  { no: 99, col: 'fecha_biopsia_mama', type: 'text', default: '1845-01-01' },
  { no: 100, col: 'fecha_resultado_biopsia_mama', type: 'text', default: '1845-01-01' },
  { no: 101, col: 'resultado_biopsia_mama', type: 'integer', default: 0 },
  { no: 102, col: 'cop_por_persona', type: 'integer', default: 0 },
  { no: 103, col: 'fecha_toma_hemoglobina', type: 'text', default: '1845-01-01' },
  { no: 104, col: 'resultado_hemoglobina', type: 'numeric', default: 0 },
  { no: 105, col: 'fecha_toma_glicemia_basal', type: 'text', default: '1845-01-01' },
  { no: 106, col: 'fecha_toma_creatinina', type: 'text', default: '1845-01-01' },
  { no: 107, col: 'resultado_creatinina', type: 'numeric', default: 0 },
  { no: 108, col: 'preservativos_entregados_its_fecha', type: 'text', default: '1845-01-01' },
  { no: 109, col: 'resultado_psa', type: 'numeric', default: 0 },
  { no: 110, col: 'fecha_tamizaje_hepatitis_c', type: 'text', default: '1845-01-01' },
  { no: 111, col: 'fecha_toma_hdl', type: 'text', default: '1845-01-01' },
  { no: 112, col: 'fecha_toma_baciloscopia', type: 'text', default: '1845-01-01' },
  { no: 113, col: 'resultado_baciloscopia', type: 'integer', default: 21 },
  { no: 114, col: 'clasificacion_riesgo_cardiovascular', type: 'integer', default: 0 },
  { no: 115, col: 'tratamiento_sifilis_gestacional', type: 'integer', default: 0 },
  { no: 116, col: 'tratamiento_sifilis_congenita', type: 'integer', default: 0 },
  { no: 117, col: 'clasificacion_riesgo_metabolico', type: 'integer', default: 0 },
  { no: 118, col: 'fecha_toma_trigliceridos', type: 'text', default: '1845-01-01' },
];

const NON_DEFAULT_SENTINEL_COLUMNS = [
  'tipo_identificacion', 'numero_identificacion', 'primer_apellido',
  'primer_nombre', 'fecha_nacimiento', 'sexo'
];

export function getFieldDefinitions() {
  return FIELD_DEFINITIONS;
}

export function getColumnNames() {
  return FIELD_DEFINITIONS.map(f => f.col);
}

export function isNonDefaultValue(columnName, value) {
  if (value === null || value === undefined) return false;
  const field = FIELD_DEFINITIONS.find(f => f.col === columnName);
  if (!field) return false;
  if (NON_DEFAULT_SENTINEL_COLUMNS.includes(columnName)) return value !== null;
  return value !== field.default;
}

export function getDefaultForColumn(columnName) {
  const field = FIELD_DEFINITIONS.find(f => f.col === columnName);
  return field ? field.default : null;
}
